### ISSUE TITLE
NetworkAdapter add two properties: GUID, PNPDeviceID

### ISSUE THREAD

**Issue by jafsuen** [Jinjinov/Hardware.Info#16]
GUID and PNPDeviceID can help determine the adapter is a physical device or not. 
Can use informations in registery:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Network\{4D36E972-E325-11CE-BFC1-08002BE10318}

**Comment by Jinjinov** [comment]
Please provide more information, some links, a detailed explanation and some example code.
