### ISSUE TITLE
Crashes on Windows Server 2016

### ISSUE THREAD

**Issue by johnds1974** [Jinjinov/Hardware.Info#19]
### Library version
1.1.1.1

### OS & OS version
Windows Server 2016 x64 (HyperV VM)

### Describe the bug

My sample application, which is essentially a copy of your sample code from GitHub simply crashes when running on Win Server 2016.
The application is .NET 5, published as self-contained and as SingleFile:

dotnet publish -r win-x64 -v n /p:PublishSingleFile=true --sc

### To Reproduce

using System;
using HardwareInformation;
using Hardware.Info;

namespace Test.HardwareInformation
{
    class Program
    {

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            HardwareInformation_1();

            Console.WriteLine("Press any key to get exit...");
            Console.ReadLine();
        }
        private static void HardwareInformation_1()
        {
            try
            {
                Console.WriteLine("HardwareInformation_1: Gathering hardware info...");

                var hi = new HardwareInfo();

                hi.RefreshAll();

                 Console.WriteLine("---------------------------------------------------------------------------");
                Console.WriteLine($"BatteryList:");
                foreach(var hw in hi.BatteryList)
                {
                    Console.WriteLine(hw);
                }
         }
            catch (Exception ex)
            {
                Console.WriteLine($"ERROR: {ex}");
            }
        }
    }
}

### Exceptions (if any)

ERROR: System.PlatformNotSupportedException: The native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll' does not have all required functions. Please, update the .NET Framework.
   at System.Management.WmiNetUtilsHelper.<>c__DisplayClass104_0.<LoadPlatformNotSupportedDelegates>b__39(Int32 _, IntPtr __, APTTYPE& ___)
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.SelectQuery..ctor(String queryOrClassName)
   at Hardware.Info.Windows.HardwareInfoRetrieval.GetOsVersionByWmi()
   at Hardware.Info.Windows.HardwareInfoRetrieval..ctor(Nullable`1 enumerationOptionsTimeout)
   at Hardware.Info.HardwareInfo..ctor(Boolean useAsteriskInWMI, Nullable`1 timeoutInWMI)
   at Test.HardwareInformation.Program.HardwareInformation_1()

### Expected behavior

It should not crash, and should display the battery information.

**Comment by Jinjinov** [comment]
You don't have the right version of the .NET installed. As the exception says:

> Please, update the .NET Framework.

Try to install .NET Core 3.1 SDK and run the `Hardware.Info.Test` project.

**Comment by johnds1974** [comment]
Thanks @Jinjinov for the suggestion. It's a curious dependency exception that one because my project is **self-contained**, which means I should not require any preinstalled SDK/Runtime. **This is a definite requirement I have - no pre-installed dependencies are allowed**.

I'm trying to investigate if System.Management, the .Net Core package, has any strange dependency on .Net classic framework.

BTW, great job on your package so far, I am keen to test all of it's capabilities, across all flavours of Operating Systems on which .Net Core can run. ;-)

**Comment by Jinjinov** [comment]
Unfortunately I don't have the time to investigate this in depth. You can try replacing `<TargetFramework>netstandard2.0</TargetFramework>` with `net5.0` in my library and recompile it.

If you do find something that I can change to make it work, please let me know.

I am glad that you like the package. I tried to make it work on every OS, but I couldn't find how to do it for all, so some code was contributed by others. If you know how to add any missing feature, all pull requests are welcome :)
