### ISSUE TITLE
Linux environment broke?

### ISSUE THREAD

**Issue by misaka00251** [Jinjinov/Hardware.Info#20]
### Library version

1.1.1.1

### OS & OS version

Arch Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/3908746/151564344-0a190d92-f5f1-4d76-aef7-9acb43f9e49e.png)

Only can get cpu & memory status on Linux environment.

### To Reproduce

Like DriveList:

```
hardwareInfo.RefreshDriveList();
var disktotal = hardwareInfo.DriveList.Count; // it's 0
```

**Comment by Jinjinov** [comment]
I only tested it on Debian and Ubuntu. There are a lot of system calls to get the hardware info on Linux. Perhaps those calls don't work on Arch.

Take a look at: https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Linux/HardwareInfoRetrieval.cs#L271

Does `lshw -class disk` work in your terminal?

**Comment by misaka00251** [comment]
Yes, it works:

```
WARNING: you should run this program as super-user.
  *-namespace:0             
       description: NVMe disk
       physical id: 0
       logical name: hwmon2
  *-namespace:1
       description: NVMe disk
       physical id: 2
       logical name: /dev/ng0n1
  *-namespace:2
       description: NVMe disk
       physical id: 1
       bus info: nvme@0:1
       logical name: /dev/nvme0n1
       configuration: wwid=eui.0025388501d2d353
  *-namespace:0
       description: NVMe disk
       physical id: 0
       logical name: hwmon1
  *-namespace:1
       description: NVMe disk
       physical id: 2
       logical name: /dev/ng1n1
  *-namespace:2
       description: NVMe disk
       physical id: 1
       bus info: nvme@1:1
       logical name: /dev/nvme1n1
       configuration: wwid=eui.a428b700a6610041
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

**Comment by Jinjinov** [comment]
well, actually, it doesn't work as it should:
`WARNING: you should run this program as super-user.`
and
`WARNING: output may be incomplete or inaccurate, you should run this program as super-user.`
mean that my library can't get the necessary info when running these commands.

did you try running my library as a super user?

**Comment by misaka00251** [comment]
Well I installed a fresh Ubuntu 20.04 and login as root.

The command works fine:

![image](https://user-images.githubusercontent.com/3908746/152285943-f5807a6c-d028-4a11-bc0a-96caffb2ae55.png)

While `hardwareInfo.DriveList` don't:

![image](https://user-images.githubusercontent.com/3908746/152286020-428b9fa2-f943-4dec-996a-5c64e22eff3f.png)

**Comment by Jinjinov** [comment]
I will take a look at this.

**Comment by Jinjinov** [comment]
I made a new NuGet package version.

**Comment by misaka00251** [comment]
Yeah, the new version works on Ubuntu, guess I just drop support for other distro now 🤣
