### ISSUE TITLE
Cannot run in Linux, prompting the following error

### ISSUE THREAD

**Issue by hyzgit** [Jinjinov/Hardware.Info#21]
Linux os:
Linux HikvisionOS 3.10.0-957.12.2.el7.x86_64 #1 SMP Mon Jul 15 17:56:54 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

Error message:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Hardware.Info, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Hardware.Info, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'
Aborted

**Comment by Jinjinov** [comment]
You get `FileNotFoundException` for assembly `Hardware.Info`. That means that your project doesn't build correctly. Your executable application can't find the assembly file of my library.

What are you using to build the project on Linux? Visual Studio Code? JetBrains Rider?

Can you show me your project file / your make file?
