### ISSUE TITLE
Any chance to add support for Android and iOS devices?

### ISSUE THREAD

**Issue by Jakar510** [Jinjinov/Hardware.Info#26]
Any chance to add support for Android and iOS devices? I'm aware some things probably won't work, but it would be awesome if this library could support it.

Mainly looking for:
Cpu (serial number?)
Memory
Motherboard

**Comment by Jinjinov** [comment]
I am looking at how to identify Android and iOS

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.osplatform?view=net-6.0
|  |  |
| --- | --- |
| FreeBSD	| Gets an object that represents the FreeBSD operating system. |
| Linux	| Gets an object that represents the Linux operating system. | 
| OSX		| Gets an object that represents the OSX operating system. | 
| Windows	| Gets an object that represents the Windows operating system. | 

https://docs.microsoft.com/en-us/dotnet/api/system.platformid?view=net-6.0

| |  | |
--- | --- | ---
MacOSX	| 6	| The operating system is Macintosh. This value was returned by Silverlight. On .NET Core, its replacement is Unix.
Other	| 7	| Any other operating system. This includes Browser (WASM).
Unix		| 4	| The operating system is Unix.
Win32NT	| 2	| The operating system is Windows NT or later.
Win32S	| 0	| The operating system is Win32s. This value is no longer in use.
Win32Windows	| 1 | The operating system is Windows 95 or Windows 98. This value is no longer in use.
WinCE	| 3 | The operating system is Windows CE. This value is no longer in use.
Xbox	| 5 | The development platform is Xbox 360. This value is no longer in use.

**Comment by Jinjinov** [comment]
OK, I found a way to determine if the code is running on Android or iOS

https://docs.microsoft.com/en-us/dotnet/api/system.operatingsystem?view=net-6.0

**Comment by Jinjinov** [comment]
I have looked how to get hardware info for mobile, but I have not found anything useful.

I found these:
https://learn.microsoft.com/en-us/xamarin/essentials/device-information?tabs=ios
https://learn.microsoft.com/en-us/dotnet/api/android.os.hardwarepropertiesmanager?view=xamarin-android-sdk-12

But they don't have the necessary info.
I will close this ticket for now.
