### ISSUE TITLE
Cannot get MonitorList.

### ISSUE THREAD

**Issue by kelicto** [Jinjinov/Hardware.Info#27]
I cannot any monitor by WMI API. I've wrapped it myself and it doesn't seem to be easy to get this information. Have you ever encountered this problem?

I found it impossible to get them using the handle method. I had to use a keystroke script(such as autoit) to get the content, but it was a little less elegant.

Speccy:
![image](https://user-images.githubusercontent.com/23723575/190046544-aeef6b2a-0546-402d-a053-81164bf415d5.png)
![image](https://user-images.githubusercontent.com/23723575/190046397-2547e2e0-53e5-46b2-b619-2930477ed68d.png)

**Comment by Jinjinov** [comment]
Please fill out the New issue Bug template, otherwise I can't help you.

**Comment by kelicto** [comment]
There is nothing to fill in the template. Also, the so-called Q&A site is not a good answer to this question, which is why it is asked here. If you can't solve it, there will be useful twists and turns to solve it.

**Comment by Jinjinov** [comment]
There is only one question in your comment:

> Have you ever encountered this problem?

The answer is: No, I haven't.

**Comment by kelicto** [comment]
![image](https://user-images.githubusercontent.com/23723575/190537558-e3a7d1c9-6eab-4c1b-b3a6-bc32e91365da.png)

I myself have long written based on the same code as you essentially, without any effect. A slightly better way is to analyze the registry, but it's still not very accurate.

WMI does not solve all the problems, at least not in terms of getting the monitor model.

**Comment by Jinjinov** [comment]
Yes, I agree, WMI doesn't solve all the problems. I had many more problems with WMI in my other project https://github.com/Jinjinov/Usb.Events

What really helped me there was the use of `Solarwinds WMI Monitor`. I knew what result I was looking for and I searched the WMI, looking where this information might be. I found it in a different place from where I expected it.

Perhaps you can use `Solarwinds WMI Monitor` and search for `U2412M` and perhaps you will find it somewhere in WMI.

**Comment by kelicto** [comment]
Thank you very much, I will try it.

**Comment by kelicto** [comment]
I've solved the obstacle I've encountered so far, and I hope you can break through it. This part of the code, at the moment, is used internally in the company, so I can't send it out.
