### ISSUE TITLE
Check if the current account has permissions to use WMI

### ISSUE THREAD

**Issue by adhip94** [Jinjinov/Hardware.Info#28]
**Is your feature request related to a problem? Please describe.**
Is it possible to create a method to check if the user account/current account has permissions to use WMI? Or during initialization throw an exception indicating the same?

**Describe the solution you'd like**
A method or an exception while initializing the class indicating the user does not have permissions to use WMI

**Describe alternatives you've considered**
None yet.

**Additional context**
None.

**Comment by Jinjinov** [comment]
I have never hear that WMI would require permissions to use on the local machine.

According to this, you don't need any special permissions:
https://stackoverflow.com/questions/24295301/does-wmi-access-in-net-required-administrative-privileges

You only need permissions to use WMI on a remote computer, but my library doesn't do that.

Do you have an example where `Hardware.Info` would require any special permissions?

**Comment by adhip94** [comment]
I have a customer who uses [this](https://www.dizzion.com/wp-content/uploads/2020/03/dizzion-zlink-srw-end-point-data-sheet.pdf) on their machines. In this case our application which uses Hardware.Info to verify if ram, disk storage etc. is available at startup fails since application is not able to access underlying OS functionalities, which causes WMI to fail. Hence I requested for a method/check to verify if WMI is accessible or not.

**Comment by Jinjinov** [comment]
I see. It would really help me if you would provide me with the steps to replicate this failure, so I would know what the problem is.

Just show me the minimal code necessary for this failure to happen.

**Comment by Jinjinov** [comment]
I didn't find any mentions of WMI failing on a local machine due to lack of permissions.

If you don't show me how this failure happens - what exception is thrown - then I can't do anything to fix it.
