### ISSUE TITLE
Expose method to get the Windows OS version

### ISSUE THREAD

**Issue by adhip94** [Jinjinov/Hardware.Info#29]
**Is your feature request related to a problem? Please describe.**
Retrieve the Windows OS version

**Describe the solution you'd like**
Want to retrieve the Windows OS version.

**Describe alternatives you've considered**
Currently using `ManagementObjectSearcher` to get the OS version used
```C#
using (ManagementObjectSearcher searcher = new ManagementObjectSearcher("SELECT Caption FROM Win32_OperatingSystem"))
{
      foreach (ManagementObject os in searcher.Get())
      {
         OSCaption = os["Caption"].ToString();
         break;
      }
}
```

**Additional context**
I have seen methods being called to get the windows OS version [here](https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Windows/HardwareInfoRetrieval.cs#L53). Is it possible to expose this so we can use this in our application to detect the windows version.

**Comment by Jinjinov** [comment]
Yes, it is possible to expose this method, but... I try to keep this library as cross platform as possible - if I make a new method, I try to implement it in Windows, Linux and macOS.

I could make `GetOsVersion()` for all three operating systems.

**Comment by Jinjinov** [comment]
Done: https://github.com/Jinjinov/Hardware.Info/releases/tag/v10.0.1.1
