### ISSUE TITLE
Add CPU total usage and for each CPU core and also network throughput of each interface

### ISSUE THREAD

**Issue by isenmann** [Jinjinov/Hardware.Info#3]
Add more information to the Hardware.Info project, precisely add usage for each CPU core and overall CPU usage and also add network throughput for each interface.

**Comment by Jinjinov** [comment]
Thank you for your contribution.

Do you have any plans to implement these features for Linux and macOS?

**Comment by isenmann** [comment]
I will do it for Linux in the near future, that should be possible, but for macOS I can't do it because I don't have one.

**Comment by Jinjinov** [comment]
I have changed the names of the properties and functions to be more consistent with the project: b11802cd7a2273a30b3a894524a99a0538230393

I also made a new release and NuGet package: https://github.com/Jinjinov/Hardware.Info/releases/tag/v1.0.1.0

I am looking forward to the Linux code :)

**Comment by isenmann** [comment]
@Jinjinov For doing the network throughput in Linux I would like to use another command line tool (ifstat). How do you handle such requirements? Is it "allowed" to do so? 

Just asking before I start with coding.

**Comment by isenmann** [comment]
The missing macOS code won't be done by me, so from my side you can close this issue. Or keep it open to have it as a reminder that macOS code is missing.

**Comment by Jinjinov** [comment]
@isenmann Thank you for your contributions!
