### ISSUE TITLE
Invalid Class exception when using RefreshCPUList method

### ISSUE THREAD

**Issue by C6OI** [Jinjinov/Hardware.Info#30]
### Library version
10.0.1.1
### OS & OS version
Windows 10 x64 21H2 build 19044
### Describe the bug
`RefreshCPUList()` method occurs the `InvalidClass` exception

### To Reproduce
```cs
internal static class Program {
    static readonly IHardwareInfo HardwareInfo = new HardwareInfo();
    
    public static void Main() {
        HardwareInfo.RefreshMemoryStatus();
        HardwareInfo.RefreshCPUList(); // Exception
        
        Console.WriteLine(HardwareInfo.MemoryStatus);
        HardwareInfo.CpuList.ForEach(Console.WriteLine);
    }
}
```
1. Open Visual Studio and create a new ConsoleApplication
2. Add the code above
3. Run the program

### Exceptions
Unhandled exception. System.Management.ManagementException: Invalid class
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Hardware.Info.Windows.HardwareInfoRetrieval.GetCpuList(Boolean includePercentProcessorTime)
   at Hardware.Info.HardwareInfo.RefreshCPUList(Boolean includePercentProcessorTime)
   at ConsoleApp1.Program.Main() in C:\Users\Stm07\Desktop\ConsoleApp1\Program.cs:line 10

### Expected behavior
Writing CPU info to the console

**Comment by Jinjinov** [comment]
I tried running the exact code you wrote in the comment and it works without a problem on my PC.

I tried running it in `debug` and in `release`, from Visual Studio and from command line and it always works.

Can you give me some more info?
- your Visual Studio version
- your .NET SDK version
- is your Windows user account Guest or Admin?
- did you run Debug or Release?
- did you run from Visual Studio or from command line?
- do you also get an exception if you try `IHardwareInfo _hardwareInfo = new HardwareInfo(useAsteriskInWMI: false);` ?
- do you also get an exception if you try `hardwareInfo.RefreshCPUList(includePercentProcessorTime: false);` ?
- do you also get an exception if you try `hardwareInfo.GetDriveList();` or `hardwareInfo.RefreshMemoryList()` ?
- what are the exception details for `System.Management.ManagementException: Invalid class` ?

**Comment by C6OI** [comment]
* Visual Studio 2022/Rider 2022.2.2/PowerShell 5.1
* .NET 6.0.401
* I ran it in both Debug and Release
* I ran it in JetBrains Rider, Visual Studio and PowerShell
* My Windows account is an Admin
* This also happens with `Hardware.Info 10.0.1`
* This doesn't happen with `hardwareInfo.RefreshCPUList(includePercentProcessorTime: false);`
* This doesn't happen with `HardwareInfo.RefreshDriveList();` or `HardwareInfo.RefreshMemoryList();`

All exception details that I was able to get:
```
System.Management.ManagementException
  HResult=0x80131501
  Message = Invalid class
  Source = System.Management
  StackTrace:
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Hardware.Info.Windows.HardwareInfoRetrieval.GetCpuList(Boolean includePercentProcessorTime)
   at Hardware.Info.HardwareInfo.RefreshCPUList(Boolean includePercentProcessorTime)
   at Program.Main() в C:\Users\Stm07\Desktop\ConsoleApp1\Program.cs:line 8
```

**Comment by Jinjinov** [comment]
Thank you for all the info!

If this doesn't happen with `hardwareInfo.RefreshCPUList(includePercentProcessorTime: false);` then the error must be somewhere between 
https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Windows/HardwareInfoRetrieval.cs#L230
and 
https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Windows/HardwareInfoRetrieval.cs#L255

Can you please try with `IHardwareInfo hardwareInfo = new HardwareInfo(useAsteriskInWMI: false);` ?

If that doesn't work, can you debug `Hardware.Info.Test` and put a breakpoint at 
https://github.com/Jinjinov/Hardware.Info/blob/master/Hardware.Info/Windows/HardwareInfoRetrieval.cs#L234
and then step line by line and tell me the line where the exception is thrown?

**Comment by C6OI** [comment]
Oh, I didn't notice that I didn't write about it. I tried changing `IHardwareInfo hardwareInfo = new HardwareInfo(useAsteriskInWMI: false);`, but the program also crashes.

Sorry, but I'm not at the computer now, I can try to debug it tomorrow.

**Comment by C6OI** [comment]
I debugged it and the exception is thrown on the next line:
![image](https://user-images.githubusercontent.com/59257047/193737803-0a5b3fef-c53f-463f-ad51-d08b29fe80db.png)

**Comment by Jinjinov** [comment]
There are not many results when searching for `Win32_PerfFormattedData_PerfOS_Processor` errors

I found these:
https://stackoverflow.com/questions/67674042/invalid-query-on-win32-perfformatteddata-perfos-processor

https://social.technet.microsoft.com/wiki/contents/articles/19374.windows-performance-monitor-unable-to-add-these-counters.aspx
It says you should run `lodctr /r` from `C:\WINDOWS\System32` to rebuild performance counters on your PC.

Perhaps this error happens only on your PC. Can you try running `Hardware.Info.Test` on another PC?

I will also look into this:
https://stackoverflow.com/questions/9777661/returning-cpu-usage-in-wmi-using-c-sharp
It says you can get CPU usage with `select LoadPercentage from Win32_Processor` or `select LoadPercentage from CIM_Processor` so I would not use `select PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor`

**Comment by C6OI** [comment]
> It says you should run `lodctr /r` from `C:\WINDOWS\System32` to rebuild performance counters on your PC.  

This command didn't help me

> Perhaps this error happens only on your PC. Can you try running `Hardware.Info` on another PC?

I asked my friend to run it, he ran it and the program worked without exceptions

**Comment by Jinjinov** [comment]
I see. Thank you for trying everything.

I suggest you use `hardwareInfo.RefreshCPUList(includePercentProcessorTime: false);` on your PC until I fix this. The only difference is that `PercentProcessorTime` will be zero.

I will put `select PercentProcessorTime from Win32_PerfFormattedData_PerfOS_Processor` inside a `try catch` block, and if the `ManagementException` is thrown, I will use `select LoadPercentage from Win32_Processor` as a backup.

**Comment by Jinjinov** [comment]
Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v10.1.0.0
