### ISSUE TITLE
RefreshCPUList ThrowNoMatchException

### ISSUE THREAD

**Issue by glebov21** [Jinjinov/Hardware.Info#34]
### Library version
10.1.0.1

### OS & OS version
Debian GNU/Linux 11 (KVM)

### Note
Command working fine on windows.

### Describe the bug

hardwareInfo.RefreshCPUList(); throw ThrowNoMatchException:
"sequence contains no matching element"

 at System.Linq.ThrowHelper.ThrowNoMatchException()\n  
  at Hardware.Info.Linux.HardwareInfoRetrieval.GetCpuUsage(CPU cpu)\n 
    at Hardware.Info.Linux.HardwareInfoRetrieval.GetCpuList(Boolean includePercentProcessorTime)\n 

### To Reproduce
1) publish as linux-x64, release, net-core 6.0
2) execute RefreshCPUList()

**Comment by Jinjinov** [comment]
Thank you for reporting this. I will look into it.

**Comment by Jinjinov** [comment]
Here is the new NuGet: https://github.com/Jinjinov/Hardware.Info/releases/tag/v10.1.1.0

Is this issue resolved now?

**Comment by glebov21** [comment]
> Here is the new NuGet: https://github.com/Jinjinov/Hardware.Info/releases/tag/v10.1.1.0
> 
> Is this issue resolved now?

sorry, i will try to test only on sunday and answer to you :)
