### ISSUE TITLE
CurrentClockSpeed isn't correctly calculated on Windows.

### ISSUE THREAD

**Issue by jason-c-daniels** [Jinjinov/Hardware.Info#35]
### Library version
10.1.1

### OS & OS version
Windows 11, latest as of 2023-03-11

### Describe the bug

`cpu.CurrentClockSpeed` is incorrect on some processors. Those processors scale performance based on load. Under high load it is lower than the actual clock speed. Under light load it is higher than the actual clock speed. In fact it always the same as `cpu.MaxClockSpeed`.

#### Context
Modern CPUs can scale their performance. The code for this library only uses WMI queries. WMI does not appear to account for this fact.

The correct calculation for those sorts of CPUs is to scale the maximum CPU speed returned by the current WMI query being done by the **Windows Performance Counter**: *\Processor Information(_Total)\% Processor Performance*

This [SO question](https://stackoverflow.com/questions/61802420/unable-to-get-current-cpu-frequency-in-powershell-or-python) has the correct calculation in the answer. 

#### Physical Environment.
1. Use a computer with a processor that scales its performance based on load.  **This is a critical element in reproducing this issue.**
2. Run Windows 11. (More likely than not Win8+ will be fine)

Example processor: *12th Gen Intel(R) Core(TM) i7-12700H*

#### Steps

1. Place your CPU under heavy load.
2. Go to Device Manager and observe your CPU speed. (In my case it reads roughly 3.4-3.5GHz)
3. Run `HardwareInfo.RefreshCPUList()` while under heavy load.

#### Expected Result
When my CPU, which is 2.3Ghz, is at 150% `ProcessorPerformance` I should get 3450 for `cpu.CurrentClockSpeed`.

#### Actual Result
`cpu.CurrentClockSpeed` reads 2300.

As for this: `If you don't provide C# code to reproduce the problem, the issue will be closed.`
Since this is hardware specific, and I've pinpointed the root cause, the correct calculation, and an StackOverflow article with code you should be able to all but copy and paste from, you should have all the *information* you need to proceed, for Windows. Hardware may be a different story. I don't know about Macs or Linux. 
*So, please make an exception.* You will need to get the right hardware... or someone with it willing to run the code and report findings... **I'm willing to be that guinea pig.**

**Comment by Jinjinov** [comment]
I will look into it, but I can't test it. Your help with testing would be appreciated :)

**Comment by Jinjinov** [comment]
Please test the solution before I make a NuGet :)

**Comment by jason-c-daniels** [comment]
Will do. Is it ready?

**Comment by jason-c-daniels** [comment]
First, thanks for the fast response time.
**Second. It looks great.**

Here's the code I ran:
```csharp
        static void Main(string[] _)
        {
            var hwi = new HardwareInfo(false);
            hwi.RefreshAll();
            for (int i = 0; i < 240; i++)
            {
                var sw = Stopwatch.StartNew();
                hwi.RefreshCPUList(false);
                sw.Stop();
                Thread.Sleep(250);
                var cs=hwi.CpuList[0].CurrentClockSpeed / 1000f;
                Console.WriteLine($"Current Clock Speed: {cs:n2} GHz; Retrieval Time: {sw.Elapsed.TotalMilliseconds:n3} ms");
            }
            //BenchmarkRunner.Run(typeof(Program).Assembly);
        }

```
Results:
```text
Current Clock Speed: 1.18 GHz; Retrieval Time: 17.694 ms
Current Clock Speed: 3.12 GHz; Retrieval Time: 21.520 ms
Current Clock Speed: 2.68 GHz; Retrieval Time: 24.264 ms
Current Clock Speed: 1.16 GHz; Retrieval Time: 25.740 ms
Current Clock Speed: 1.77 GHz; Retrieval Time: 21.549 ms
Current Clock Speed: 1.59 GHz; Retrieval Time: 22.518 ms
Current Clock Speed: 1.29 GHz; Retrieval Time: 24.266 ms
Current Clock Speed: 1.35 GHz; Retrieval Time: 28.817 ms

```

**Comment by Jinjinov** [comment]
https://www.nuget.org/packages/Hardware.Info/10.1.1.1

**Comment by jason-c-daniels** [comment]
You're awesome!
