### ISSUE TITLE
Multithread usage questions

### ISSUE THREAD

**Issue by atomknack** [Jinjinov/Hardware.Info#36]
Thank you for such great library! I have 3 questions with decreasing importance.

1) Can this library be used in separate thread from main. I mean is can `new HardwareInfo()`, `.RefreshAll()`, and all properties be accessed from one child thread that is not main, is there is some possible caveats?
2) Less important: Can one object `HardwareInfo `be used by multiple threads, is it thread safe?
3) Even more less important: Can it be used in async context?

**Comment by Jinjinov** [comment]
I am glad you like it. I never tried using it from another thread.

1. There is no reason why it wouldn't work from another thread. Usually running from the main thread is only important for the user interface methods, especially when dealing with events.
2. No, `HardwareInfo` is not thread safe. If you call `RefreshAll()` from one thread, you can't safely access the public properties from another thread. You could make it thread safe by using `lock` on, (for example) `List<CPU> CpuList` and calling `RefreshCPUList()` in one thread and using another `lock` on `List<CPU> CpuList` where you read it in another thread.
3. What do you mean by `used in async context` ? Any synchronous method can be called from a `async` method without a problem. Do you mean if you can `await RefreshAll()` ? No, you can't `await` it directly, but you can use `await Task.Run(() => hardwareInfo.RefreshAll());` to run it in another thread - just remember that `RefreshAll()` has to finish before you can access the results.
