### ISSUE TITLE
Not work in console app

### ISSUE THREAD

**Issue by yuanrui** [Jinjinov/Hardware.Info#39]
### Library version
11.0.0.1

### OS & OS version
Windows 11 

### Describe the bug
RefreshAll() method throw System.Management currently is only supported for Windows desktop applications.

### To Reproduce
```
IHardwareInfo hardwareInfo = new HardwareInfo();
hardwareInfo.RefreshAll();
```

### Dotnet runtime
.net core 3.1

**Comment by Jinjinov** [comment]
Use .NET 6 or .NET 7

Support for .NET Core 3.1 ended on Dec 13, 2022
Support for .NET 5 ended on May 10, 2022

https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by yuanrui** [comment]
I tested v10.1.1 is working in .net core 3.1, and updated System.Management for v6.0.1
So the dependency nuget package System.Management maybe change for v6.0.1 is better.
