### ISSUE TITLE
VideoController.AdapterRAM does not report > 4GB

### ISSUE THREAD

**Issue by jesperll** [Jinjinov/Hardware.Info#40]
### Library version
11.0.0.1

### OS & OS version
Windows 11 22H2 (but the bug is on ALL versions of Windows)

### Describe the bug
VideoController.AdapterRAM is a 32 bit unsigned int and therefore limited to represent 4GB. The Windows code fills the value using WMI which unfortunately has the same bug. Any video controller with more than 4GB will be reported as having 4GB by WMI
(see https://www.google.com/search?q=wmi+adapterram+4gb)

### To Reproduce
On a windows machine with a video controller with more than 4GB dedicated memory

var info = new HardwareInfo();
info.RefreshVideoControllerList();
var ram = info.VideoControllers[0].AdapterRAM;

### Expected behavior
Actual amount of memory should be reported

**Comment by Jinjinov** [comment]
Thank you for reporting this issue. I will try to find a workaround ASAP.

**Comment by Jinjinov** [comment]
I found a workaround with windows registry, but I don't have a graphics card with more than 4 GB RAM.

It would be great if you could download Hardware.Info and run Hardware.Info.Test to check if it is working.

**Comment by jesperll** [comment]
It works - but I sent you a PR with a bit simpler code that I wrote after creating the issue yesterday.

**Comment by Jinjinov** [comment]
Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v11.0.1.0
