### ISSUE TITLE
System.Management currently is only supported for Windows desktop applications

### ISSUE THREAD

**Issue by Small-North** [Jinjinov/Hardware.Info#45]
![image](https://github.com/Jinjinov/Hardware.Info/assets/43372031/57806530-0c59-4a27-a336-9cd5ee8a3aaf)
Only run in Windows?

**Comment by Small-North** [comment]
environment：.net core 3.1 win10

**Comment by Jinjinov** [comment]
.net core 3.1 is not supported: https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core

**Comment by Small-North** [comment]
Thanks，Have you collected information on CPU usage?
