### ISSUE TITLE
PercentProcessorTime is always zero on Linux

### ISSUE THREAD

**Issue by goodtogood** [Jinjinov/Hardware.Info#5]
Hi,
great work.
but I found PercentProcessorTime is always zero on Linux.
Is it a bug or missing feature?
thanks

**Comment by Jinjinov** [comment]
Thanks!
PercentProcessorTime was added in Windows by https://github.com/isenmann just 19 days ago.
He said that he will also add it in Linux, that is why issue #3 is still open - I am waiting for his merge request.

**Comment by isenmann** [comment]
I still want to add it, didn't forget it. But didn't found the time to do so yet. 😉

**Comment by goodtogood** [comment]
I see .

**Comment by isenmann** [comment]
Just to mention it here, I have implemented it and opened a pull request #6

**Comment by Jinjinov** [comment]
@goodtogood https://github.com/Jinjinov/Hardware.Info/releases/tag/v1.0.1.1

**Comment by goodtogood** [comment]
@isenmann @Jinjinov 
It's great ! thanks
