### ISSUE TITLE
 CPU usage

### ISSUE THREAD

**Issue by qiuyoo** [Jinjinov/Hardware.Info#54]
**Is your feature request related to a problem? Please describe.**
I'm often frustrated because I need a way to calculate CPU usage, but I'm unsure of the best approach.

**Describe the solution you'd like**
I would like a straightforward method for obtaining the CPU usage percentage of the system, whether it's through a specific library, API, or another means.

**Describe alternatives you've considered**
I've considered using the System.Diagnostics.PerformanceCounter class to retrieve CPU usage, but I'm also interested in knowing if there are other, more convenient methods available.

**Additional context**
I'm developing a monitoring tool that requires real-time CPU usage data. I'd like to find a solution that is cross-platform as my application will run on different operating systems.

Please provide additional context or requirements if needed, so that I can better understand your request and offer more detailed assistance.

**Comment by Jinjinov** [comment]
```
 <ItemGroup>
     <PackageReference Include="Hardware.Info" Version="100.0.0.0" />
 </ItemGroup>
```

```
 using Hardware.Info;

 class Program
 {
     static readonly IHardwareInfo hardwareInfo = new HardwareInfo();

     static void Main(string[] _)
     {
         hardwareInfo.RefreshCPUList();

         foreach (var cpu in hardwareInfo.CpuList)
         {
             Console.WriteLine(cpu);

             foreach (var cpuCore in cpu.CpuCoreList)
                 Console.WriteLine(cpuCore);
         }
     }
 }
```

**Comment by qiuyoo** [comment]
Thank You for Your Support
