### ISSUE TITLE
Use semantic versioning for package releases

### ISSUE THREAD

**Issue by Nihlus** [Jinjinov/Hardware.Info#56]
**Is your feature request related to a problem? Please describe.**
At the moment, the library appears to use some type of binary-encoded version for each of its releases. Generally, it's more useful for downstream users of the library if the release version is somewhat descriptive of the changes made to the library from the previous version to this one.

**Describe the solution you'd like**
Most software libraries use semantic versioning for its releases, indicating compatibility changes in the components of each version release (major is breaking, minor is new features, patch is a pure fix without any functionality changes). It would be nice if Hardware.Info also used this system.

https://semver.org/

**Comment by Jinjinov** [comment]
Thank you for reaching out!

Unfortunately it is too late to change the versioning, because I have some OCD tendencies.

Also, I am chaotic neutral :)

I hope you can forgive my poor sense of humor and that the library serves you well!
