### ISSUE TITLE
Curious about AOT compilation

### ISSUE THREAD

**Issue by jcyuan** [Jinjinov/Hardware.Info#65]
Hi sir, sorry this is not a bug, just curious about this lib even works fine with AOT mode, because `System.Management` is obviously not compatible with AOT mode: https://github.com/dotnet/runtime/issues/61960
so what magic did you use, sir? 
and thanks~

**Comment by Jinjinov** [comment]
I wrote this library on Jul 12, 2020 but AOT became available with .NET 7 on Nov 8, 2022

I don't know why it works with AOT :)

Perhaps it works because my code never call the methods mentioned in the link you provided:
```
ManagementClass managementClass = new ManagementClass("Win32_BaseBoard");
var instances = managementClass.GetInstances();
foreach (var obj in instances)
{
    //...
}
```

**Comment by jcyuan** [comment]
> I wrote this library on Jul 12, 2020 but AOT became available with .NET 7 on Nov 8, 2022
> 
> I don't know why it works with AOT :)
> 
> Perhaps it works because my code never call the methods mentioned in the link you provided:
> 
> ```
> ManagementClass managementClass = new ManagementClass("Win32_BaseBoard");
> var instances = managementClass.GetInstances();
> foreach (var obj in instances)
> {
>     //...
> }
> ```

thanks man~ :)
