### ISSUE TITLE
NetworkAdapter information on linux not complete

### ISSUE THREAD

**Issue by Pregath0r** [Jinjinov/Hardware.Info#71]
### Library version
100.1.1

### OS, version, architecture (32 bit / 64 bit)

Ubuntu (WSL) 64 bit, Yocto-Based embedded 64 bit and Raspbian 64bit/32bit

### Describe the bug
There are some missing values when you retreive network adapter information on linux systems.

These values are missing:
Subnet mask
Gateway
DNS

### To Reproduce

```
IHardwareInfo hardwareInfo = new HardwareInfo(useAsteriskInWMI: test);
hardwareInfo.RefreshNetworkAdapterList(includeBytesPerSec: test, includeNetworkAdapterConfiguration: test);
foreach (var hardware in hardwareInfo.NetworkAdapterList)
            {
                if (hardware.Name is "eth0")
                {
                    Console.WriteLine(hardware.Name);
                    Console.WriteLine(hardware.AdapterType);
                    Console.WriteLine(hardware.MACAddress);

                    Console.WriteLine("IP");
                    
                    foreach (var ipAddress in hardware.IPAddressList)
                    {
                        Console.WriteLine(ipAddress);
                    }
                
                    Console.WriteLine("SubnetMask");
                    foreach (var subnetMask in hardware.IPSubnetList)
                    {
                        Console.WriteLine(subnetMask);
                    }
                
                    Console.WriteLine("Gateway");
                    foreach (var gateway in hardware.DefaultIPGatewayList)
                    {
                        Console.WriteLine(gateway);
                    }
                
                    Console.WriteLine("DNS");
                    foreach (var dnsServer in hardware.DNSServerSearchOrderList)
                    {
                        Console.WriteLine(dnsServer);
                    }
                }
            }
```

1. Create a c# project with hardware.info nuget package
2. Create new HardwareInfo object and refresh network adapter list
3. Print network adapter values

### Expected behavior
The values Subnet mask, Gateway and dns are not empty

### Additional context
In class HardwareInfoRetrieval (Linux) in method GetNetworkAdapterList(...) is this part:

```
            try
            {
                networkAdapterList = base.GetNetworkAdapterList(includeBytesPersec, includeNetworkAdapterConfiguration);
            }
            catch (NetworkInformationException)
            {
                networkAdapterList = GetNetworkAdapters();
            }
```

When I swap try and catch block then all values are filled out

```
            try
            {
                networkAdapterList = GetNetworkAdapters();
            }
            catch (NetworkInformationException)
            {
                networkAdapterList = base.GetNetworkAdapterList(includeBytesPersec, includeNetworkAdapterConfiguration);
                
            }
```

**Comment by Jinjinov** [comment]
Thank you for reporting this!

**Comment by Pregath0r** [comment]
Hey,

yeah swapping was just a try of me to see what GetNetworkAdapters() delivers. Wanted to share the infos with you. I think both results can be merged to one result. If I can support you with tests or something, reach out to me!

**Comment by Jinjinov** [comment]
I took a look at `GetNetworkAdapterList` but I can't see much info because I am running Ubuntu inside a VirtualBox.

The info that I could see really confirms what you said - `GetNetworkAdapters();` provides more data than `base.GetNetworkAdapterList`

Could you change the code to this and set a breakpoint and just run the code up to the breakpoint and compare the two lists in debug watch?
```
List<NetworkAdapter> networkAdapterList;
List<NetworkAdapter> networkAdapterList2;

networkAdapterList = base.GetNetworkAdapterList(includeBytesPersec, includeNetworkAdapterConfiguration);
networkAdapterList2 = GetNetworkAdapters();
```
Can you confirm that `GetNetworkAdapters();` provides all data that `base.GetNetworkAdapterList` provides - and more?

Unfortunately the only PC where I have Linux on hardware (not in VM) is out of my reach for the moment.

**Comment by Pregath0r** [comment]
I took a look into it and compared both lists. There is a difference in the MAC-Address field:

```
base.GetNetworkAdapterList MAC format is: 00123456789A 
GetNetworkAdapters MAC format is: 00:12:34:56:78:9A
```
The value is the same but format is different.


Everything else is, in my case, the same and more.

**Comment by Jinjinov** [comment]
Thank you for verifying!

Done in https://github.com/Jinjinov/Hardware.Info/releases/tag/v100.1.1.1

**Comment by Pregath0r** [comment]
Thanks for fixing it!
